/**
 * auth.schema.ts
 * Better Auth required tables — DO NOT modify column names or types.
 * Better Auth owns these tables; we only declare them in Drizzle for
 * type-safety and to enable cross-table relations in queries.
 *
 * Docs: https://www.better-auth.com/docs/concepts/database
 */
import {
  pgTable,
  text,
  timestamp,
  boolean,
  index,
} from 'drizzle-orm/pg-core';

/**
 * Core identity record managed by Better Auth.
 * `id` is a nanoid string generated by the library.
 */
export const user = pgTable(
  'user',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull().unique(),
    emailVerified: boolean('email_verified').notNull(),
    image: text('image'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
  },
  (t) => [
    // Frequent lookup by email (login, dedup checks).
    index('user_email_idx').on(t.email),
  ],
);

/**
 * Active sessions. One user can have many sessions (multiple devices).
 * `token` is the opaque session token sent in cookies/headers.
 */
export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (t) => [
    index('session_user_id_idx').on(t.userId),
    index('session_expires_at_idx').on(t.expiresAt),
  ],
);

/**
 * OAuth / credential accounts linked to a user.
 * A user can have multiple accounts (e.g., Google + email/password).
 * `password` stores the bcrypt hash when provider is 'credential'.
 */
export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', {
      withTimezone: true,
    }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', {
      withTimezone: true,
    }),
    scope: text('scope'),
    password: text('password'), // bcrypt hash — managed by Better Auth
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
  },
  (t) => [
    index('account_user_id_idx').on(t.userId),
    index('account_provider_idx').on(t.providerId, t.accountId),
  ],
);

/**
 * Email / magic-link verification tokens.
 * `identifier` is the email address being verified.
 * `value` is the token. Both are opaque strings managed by Better Auth.
 */
export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }),
  },
  (t) => [index('verification_identifier_idx').on(t.identifier)],
);
